-- ─── Step 1: Tables (generated by Drizzle) ───────────────────────────────────

CREATE TABLE IF NOT EXISTS "chat_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"has_correction" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "flashcards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"front" text NOT NULL,
	"back" text NOT NULL,
	"example" text,
	"tags" text[] DEFAULT '{}',
	"ease_factor" real DEFAULT 2.5 NOT NULL,
	"interval_days" integer DEFAULT 1 NOT NULL,
	"repetitions" integer DEFAULT 0 NOT NULL,
	"due_date" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "lessons" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"cefr_level" text NOT NULL,
	"category" text DEFAULT 'grammar' NOT NULL,
	"content" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "room_members" (
	"room_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"joined_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "room_members_room_id_user_id_unique" UNIQUE("room_id","user_id")
);

CREATE TABLE IF NOT EXISTS "rooms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"topic" text,
	"host_id" uuid NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"max_members" integer DEFAULT 4 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "speaking_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"transcript" text,
	"feedback" jsonb,
	"duration_secs" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_errors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"error_category" text NOT NULL,
	"original_text" text NOT NULL,
	"corrected_text" text,
	"context" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_progress" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"lesson_id" uuid NOT NULL,
	"status" text DEFAULT 'not_started' NOT NULL,
	"score" integer,
	"xp_earned" integer DEFAULT 0 NOT NULL,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_progress_user_id_lesson_id_unique" UNIQUE("user_id","lesson_id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"auth_id" uuid NOT NULL,
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"cefr_level" text DEFAULT 'B1' NOT NULL,
	"goal" text DEFAULT 'general' NOT NULL,
	"domain" text DEFAULT 'general' NOT NULL,
	"accent_preference" text DEFAULT 'american' NOT NULL,
	"streak_days" integer DEFAULT 0 NOT NULL,
	"xp_total" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_auth_id_unique" UNIQUE("auth_id"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);

CREATE TABLE IF NOT EXISTS "vocabulary" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"word" text NOT NULL,
	"definition" text NOT NULL,
	"example" text,
	"cefr_level" text,
	"mastery" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vocabulary_user_id_word_unique" UNIQUE("user_id","word")
);

-- ─── Step 2: Foreign Keys ─────────────────────────────────────────────────────

ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "flashcards" ADD CONSTRAINT "flashcards_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "room_members" ADD CONSTRAINT "room_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_host_id_users_id_fk" FOREIGN KEY ("host_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "speaking_sessions" ADD CONSTRAINT "speaking_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "user_errors" ADD CONSTRAINT "user_errors_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "user_progress" ADD CONSTRAINT "user_progress_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "user_progress" ADD CONSTRAINT "user_progress_lesson_id_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."lessons"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "vocabulary" ADD CONSTRAINT "vocabulary_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;

-- ─── Step 3: Indexes ──────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS "idx_chat_messages_user" ON "chat_messages" USING btree ("user_id","created_at");
CREATE INDEX IF NOT EXISTS "idx_flashcards_user_due" ON "flashcards" USING btree ("user_id","due_date");
CREATE INDEX IF NOT EXISTS "idx_user_errors_user" ON "user_errors" USING btree ("user_id","created_at");

-- ─── Step 4: RLS ──────────────────────────────────────────────────────────────

ALTER TABLE users              ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons            ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress      ENABLE ROW LEVEL SECURITY;
ALTER TABLE flashcards         ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocabulary         ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_errors        ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages      ENABLE ROW LEVEL SECURITY;
ALTER TABLE speaking_sessions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms              ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_members       ENABLE ROW LEVEL SECURITY;

-- users
CREATE POLICY "users_select" ON users FOR SELECT USING (auth_id = auth.uid());
CREATE POLICY "users_insert" ON users FOR INSERT WITH CHECK (auth_id = auth.uid());
CREATE POLICY "users_update" ON users FOR UPDATE USING (auth_id = auth.uid());

-- lessons: public read
CREATE POLICY "lessons_read" ON lessons FOR SELECT USING (true);

-- own-data tables
CREATE POLICY "own_progress"   ON user_progress    USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "own_flashcards" ON flashcards        USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "own_vocabulary" ON vocabulary        USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "own_errors"     ON user_errors       USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "own_chat"       ON chat_messages     USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "own_speaking"   ON speaking_sessions USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));

-- rooms
CREATE POLICY "rooms_read"   ON rooms FOR SELECT USING (is_active = true);
CREATE POLICY "rooms_insert" ON rooms FOR INSERT WITH CHECK (host_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "rooms_update" ON rooms FOR UPDATE USING (host_id = (SELECT id FROM users WHERE auth_id = auth.uid()));

-- room_members
CREATE POLICY "room_members_read"   ON room_members FOR SELECT USING (true);
CREATE POLICY "room_members_insert" ON room_members FOR INSERT WITH CHECK (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));
CREATE POLICY "room_members_delete" ON room_members FOR DELETE USING (user_id = (SELECT id FROM users WHERE auth_id = auth.uid()));

-- ─── Step 5: auto updated_at trigger ─────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
